version: 2
sphinx:
  configuration: docs/conf.py
formats: []
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
python:
    install:
        - requirements: docs/requirements.txt
        - requirements: requirements.txt
        - method: pip
          path: .
submodules:
    include: all
    recursive: true
